// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTTwyJgTO9c1Hf_RwlhUeH90__9SHXzbw',
    appId: '1:57773129831:web:380e7b41724d04082e94c2',
    messagingSenderId: '57773129831',
    projectId: 'mychatapp-4b0de',
    authDomain: 'mychatapp-4b0de.firebaseapp.com',
    storageBucket: 'mychatapp-4b0de.appspot.com',
    measurementId: 'G-PC8H592QE7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFvOJDb4VImyw7gE9aDJR1JycPUvqs_cU',
    appId: '1:57773129831:android:bb112e7a1f95d9432e94c2',
    messagingSenderId: '57773129831',
    projectId: 'mychatapp-4b0de',
    storageBucket: 'mychatapp-4b0de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1SmHV2rSqP4CEcBUbW7YEtOX0DQS_VEk',
    appId: '1:57773129831:ios:8c75b97d7d8643822e94c2',
    messagingSenderId: '57773129831',
    projectId: 'mychatapp-4b0de',
    storageBucket: 'mychatapp-4b0de.appspot.com',
    iosClientId: '57773129831-7eum487b6ga1u7bn1h00ot75iovu82kq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSample',
  );
}
