// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqyEK65PvLIGX4jvS60RmGxUF7L4T8M2w',
    appId: '1:980978823504:web:6cba98bd75e60cd473fc55',
    messagingSenderId: '980978823504',
    projectId: 'myapp-d0d81',
    authDomain: 'myapp-d0d81.firebaseapp.com',
    storageBucket: 'myapp-d0d81.appspot.com',
    measurementId: 'G-5EF1PJMCR7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHVsawbCOU9xIe7SYZEOBGdeyQHSNGnMQ',
    appId: '1:980978823504:android:c0d1d04052ff4f5473fc55',
    messagingSenderId: '980978823504',
    projectId: 'myapp-d0d81',
    storageBucket: 'myapp-d0d81.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpiuCZabUJf2SvTW5JRqcjGcl1GcF5KxM',
    appId: '1:980978823504:ios:e6dc8afbca7b41d073fc55',
    messagingSenderId: '980978823504',
    projectId: 'myapp-d0d81',
    storageBucket: 'myapp-d0d81.appspot.com',
    iosClientId: '980978823504-g3eq7p1564l4882glo6v9mm9iq7bmh3k.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSample',
  );
}
